import lavadoClasicoPick from "../assets/img/Lavado_Clasico_220x300.jpg"
import interioresPick from "../assets/img/Limpieza_Interior_resized_220x300.jpg"
import motorPick from "../assets/img/Acondecimiento_Motor_resized_220x300.jpg"
import lavadoCompletoPick from "../assets/img/Lavado_completo220x300.jpg"
import abrillantadoPick from "../assets/img/Abrillantado_220x300.jpg"
import tratamiemtoAcrillicoPick from "../assets/img/Acrilico_resized_220x300.jpg"

export const services =  [
        { id:"lavado-clasico", name: "Lavado Clasico", image: lavadoClasicoPick, description: "Esta conpuesto por un lavado exterior y una limpieza simple del interior", price: "30.000",longDescription:'El Lavado Clásico combina una limpieza completa del exterior del vehículo con un mantenimiento interno simple, ideal para quienes buscan mantener su auto en buen estado sin un tratamiento profundo. ¿Qué incluye el servicio? Lavado exterior: Enjuague completo del vehículo, Aplicación de shampoo neutro para cuidar la pintura, Lavado de carrocería con esponjas especiales, Limpieza de llantas y guardabarros, Secado manual con paños de microfibra .  Interior básico: Aspirado de alfombras y tapizados, Limpieza de tablero, paneles y consola,Vidrios interiores y Perfumado final '},

        { id:"limpieza-interiores", name: "Limpeza de interiores", image: interioresPick, description: "Se hace una limpeza de peladeras, torpedo, bolante, butacas, alfombras tanto del piso como del techo", price: "40.000",longDescription:"La limpieza de interiores es un tratamiento profundo que elimina suciedad, manchas, olores y bacterias acumuladas en el interior del vehículo. Este servicio está diseñado para restaurar la higiene, estética y el bienestar dentro del habitáculo, proporcionando una experiencia renovada tanto para el conductor como para los pasajeros.Durante el proceso se realiza una limpieza completa de: Tapizados (tela, cuero o símil cuero), Alfombras y piso, Paneles de puertas, Tablero y consola, Techos, cinturones de seguridad y baúl, Tomas de aire, portavasos, y más"},
        { id:"acondicionamiento-motor", name: "Acondicionamiento de Motor", image: motorPick, description: "Se realiza un acondecimiento de mor el cual consiste en desengrazarlo y abrillantarlo", price: "35.000",longDescription:"El acondicionamiento de motor es un procedimiento de limpieza externa del compartimiento del motor que remueve polvo, grasa, tierra y residuos acumulados, sin afectar componentes eléctricos ni electrónicos. Este servicio está diseñado para mejorar la presentación visual del motor, facilitar su inspección y prevenir el desgaste prematuro de componentes expuestos a suciedad extrema. Incluye desengrasado superficial con productos seguros, limpieza manual con brochas y paños en zonas delicadas, aplicación de protector de plásticos y gomas del motor. "},
        { id:"lavado-completo", name: "Lavado Completo", image: lavadoCompletoPick, description: "Consite en lavado de interiores profundo, lavado de motor y lavado de chasis", price: "65.000", longDescription:"El Lavado Completo es un servicio integral diseñado para quienes buscan una renovación total del vehículo. Combina lo mejor de tres tratamientos en una sola sesión: limpieza interior profunda, lavado exterior completo y acondicionamiento del motor. Este paquete no solo mejora la estética del vehículo, sino que también aporta higiene, valor de reventa y prolonga la vida útil de múltiples componentes."},
        { id:"abrillantado", name: "Abrillantado", image: abrillantadoPick, description: "Es el proceso de abrillantado de la pintura del vehiculo con una capa de cera", price: "65.000", longDescription:"El tratamiento de abrillantado es un proceso superficial que mejora notablemente el aspecto de la pintura, devolviéndole el brillo perdido por el tiempo, el sol, la lluvia ácida y la suciedad del uso diario. A diferencia del pulido profundo o el detallado con corte, este tratamiento no elimina rayas profundas, sino que realza el color, empareja la superficie y deja una terminación brillante, suave y protegida. ¿Qué incluye? Lavado previo para eliminar residuos, aplicación de abrillantador profesional con esponja rotativa o manual, sellado final con cera o protector "},
        { id:"tratamiento-acrilico", name: "Tratamiento Acrilico", image: tratamiemtoAcrillicoPick, description: "Es el mismo procedimiento que el abrillantado agregando dos capas de Acrillico para proteger la pintura", price: "87.000", longDescription:"El tratamiento acrílico es una técnica avanzada de protección y embellecimiento de pintura que sella la superficie del vehículo con una capa acrílica. Esta capa actúa como una barrera contra agentes externos como el sol, lluvia ácida, tierra, excremento de aves y contaminantes del ambiente. A diferencia del abrillantado convencional, el acrílico ofrece brillo profundo y protección prolongada, manteniendo el auto limpio y reluciente por más tiempo."},
]